version: '3.8'

services:
  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.9.1
    hostname: wazuh.indexer
    restart: always
    environment:
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=SecretPassword123!
      - OPENSEARCH_INITIAL_ADMIN_USER=admin
    ports:
      - "9200:9200"
    volumes:
      - ./config/wazuh_indexer:/usr/share/wazuh-indexer
      - wazuh_indexer_data:/var/lib/wazuh-indexer/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  wazuh.manager:
    image: wazuh/wazuh-manager:4.9.1
    hostname: wazuh.manager
    restart: always
    user: root
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    environment:
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword123!
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration/security
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - wazuh_shared:/var/ossec/etc/shared
    depends_on:
      - wazuh.indexer

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.9.1
    hostname: wazuh.dashboard
    restart: always
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=https://wazuh.indexer:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=SecretPassword123!
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    volumes:
      - ./config/wazuh_dashboard:/usr/share/wazuh-dashboard/config
      - wazuh_dashboard_configuration:/usr/share/wazuh-dashboard/data/wazuh/config
    depends_on:
      - wazuh.indexer

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  wazuh_shared:
  wazuh_indexer_data:
  wazuh_dashboard_configuration:
